const express = require("express");
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const db = require("./database");
const scanner = require("./scanner");
const ffmpeg = require("./ffmpeg");
const poster = require("./poster");
const { resolveMediaFilePath } = require("./media-path");
const playbackIntegration = require("./playback-integration");
const remux = require("./remux");

const app = express();

app.use(express.json());


// ============================================================
// ADMIN PASSWORD
// The Admin profile's password IS the admin credential -- there's
// no separate key. It's stored as a salted scrypt hash in the
// settings table (never plaintext, never an env var), and every
// privileged request sends the raw password as x-admin-key, which
// checkAdmin verifies against the stored hash.
//
// This is basic access control for a personal home server, not a
// hardened auth system -- appropriate for keeping non-admin
// profiles (or a guest) out of admin controls.
// ============================================================

function hashPassword(password) {

    // 16-byte random salt, scrypt, stored as "salt:hash" hex.
    const salt =
        crypto.randomBytes(16).toString("hex");

    const derived =
        crypto.scryptSync(password, salt, 64).toString("hex");

    return `${salt}:${derived}`;

}

function verifyPassword(password, stored) {

    if (!stored || !stored.includes(":")) {

        return false;

    }

    const [salt, originalHash] =
        stored.split(":");

    const derived =
        crypto.scryptSync(password, salt, 64).toString("hex");

    // Constant-time comparison to avoid leaking timing info.
    const a =
        Buffer.from(originalHash, "hex");

    const b =
        Buffer.from(derived, "hex");

    return (
        a.length === b.length &&
        crypto.timingSafeEqual(a, b)
    );

}

function getStoredAdminHash() {

    const row =
        db.prepare(`
            SELECT value
            FROM settings
            WHERE key = 'admin_password_hash'
        `).get();

    return row ? row.value : null;

}

function isAdminPasswordSet() {

    return !!getStoredAdminHash();

}


// ============================================================
// EPISODE DETECTION -- thin wrappers around poster.js's shared
// implementations, so all the episode-vs-movie branching logic
// lives in one place (poster.js) rather than being duplicated.
// ============================================================

function isEpisodeFolder(folder) {

    return poster.isEpisodeFolder(folder);

}

function getShowNameFromFolder(folder) {

    return poster.getShowNameFromFolder(folder);

}


// ============================================================
// BASEFLIX WELCOME PAGE
// ============================================================

app.use(
    express.static(
        path.join(__dirname, "public")
    )
);


// ============================================================
// BASEFLIX WELCOME PAGE
// ============================================================

app.get("/", (req, res) => {

    res.sendFile(
        path.join(
            __dirname,
            "public",
            "welcome.html"
        )
    );

});


// ============================================================
// POSTERS (generated by scanner.js / ffmpeg.js, or fetched from
// TMDB) -- plus the other TMDB artwork types, each in their own
// dedicated folder alongside posters/, none of them inside
// videos/.
// ============================================================

app.use(
    "/posters",
    express.static(
        path.join(__dirname, "posters")
    )
);

app.use(
    "/backdrops",
    express.static(
        path.join(__dirname, "backdrops")
    )
);

app.use(
    "/landscapes",
    express.static(
        path.join(__dirname, "landscapes")
    )
);

app.use(
    "/logos",
    express.static(
        path.join(__dirname, "logos")
    )
);


const PORT = 4000;


// ============================================================
// CONTINUE WATCHING THRESHOLDS
// A video is considered "just started" if it has fewer than
// START_BUFFER_SECONDS watched, and "finished" if fewer than
// END_BUFFER_SECONDS remain. Both the read (GET) and write
// (POST) sides use these same constants so they can't drift
// out of sync with each other.
// ============================================================

const START_BUFFER_SECONDS = 3;
const END_BUFFER_SECONDS = 10;

const VIDEO_FOLDER =
    path.join(__dirname, "videos");

const TRANSCODED_FOLDER =
    path.join(__dirname, "transcoded");

// Where originals go once a compatible converted copy exists and
// the move is approved. Deliberately a SIBLING of videos/, not a
// subfolder of it -- if it lived inside videos/, the scanner would
// walk into it on the next scan, see the original's old path is
// "gone", and delete that video's database row (cascading away its
// Continue Watching data too). Living outside the scanned tree
// means the move is invisible to the scanner entirely.
const NOT_COMPATIBLE_FOLDER =
    path.join(__dirname, "not_compatible_originals");

if (!fs.existsSync(TRANSCODED_FOLDER)) {

    fs.mkdirSync(TRANSCODED_FOLDER, { recursive: true });

}

if (!fs.existsSync(NOT_COMPATIBLE_FOLDER)) {

    fs.mkdirSync(NOT_COMPATIBLE_FOLDER, { recursive: true });

}


// Software-encoding video at 4K in real time is expensive enough
// that it often can't keep up with playback at all. Capping
// re-encoded output at 1080p is usually the difference between a
// stream that plays and one that endlessly buffers.
const MAX_TRANSCODE_HEIGHT = 1080;


// Extension -> Content-Type for the containers Baseflicks serves
// directly. Looked up case-insensitively so "Movie.MKV" still maps.
// Anything not listed falls back to a generic binary type rather than
// being mislabelled as video/mp4 (which breaks strict browsers).
const MEDIA_CONTENT_TYPES = {
    ".mp4": "video/mp4",
    ".m4v": "video/x-m4v",
    ".webm": "video/webm",
    ".mkv": "video/x-matroska",
    ".mov": "video/quicktime",
    ".avi": "video/x-msvideo"
};

function mediaContentType(filePath) {

    const ext =
        path.extname(filePath).toLowerCase();

    return MEDIA_CONTENT_TYPES[ext] || "application/octet-stream";

}


/*
    Classify one HTTP Range header against a known file size, per
    RFC 7233. Baseflicks serves at most ONE range per response, so
    this deliberately does not implement multipart/byteranges.

    Returns exactly one of:
      { kind: "full" }                -> caller: 200 + whole file
      { kind: "unsatisfiable" }       -> caller: 416 + "bytes *&#47;<size>"
      { kind: "partial", start, end } -> caller: 206 + [start..end],
                                         both inclusive and already
                                         clamped to 0 <= start <= end
                                         <= size - 1 (no NaN, no
                                         negative, no oversized offsets)

    Classification -- first matching rule wins:
       1. no header ................................... full
       2. unit is not "bytes=" ....................... full  (unsupported unit)
       3. header contains a comma ................... full  (multi-range,
          OR list syntax with an empty element like "0-99," / ",0-99" --
          either way it is not a single range and we never emit a 206)
       4. spec is not "<digits>-<digits>" ........... full  (malformed)
          (both sides empty also counts as malformed)
       5. suffix form  "-N"  (final N bytes):
            N == 0 .................................. unsatisfiable
            size == 0 .............................. unsatisfiable
            N >= size ............................. partial 0 .. size-1
            otherwise ............................. partial size-N .. size-1
       6. normal form  "S-"  or  "S-E":
            E defaults to size-1 when absent
            size == 0 .............................. unsatisfiable
            S >= size ............................. unsatisfiable
            E < S ................................. unsatisfiable
            otherwise ............................. partial S .. min(E, size-1)
*/
function parseByteRange(rangeHeader, fileSize) {

    if (typeof rangeHeader !== "string" || rangeHeader.length === 0) {
        return { kind: "full" };
    }

    const unitMatch =
        rangeHeader.trim().match(/^bytes=(.*)$/i);

    if (!unitMatch) {
        return { kind: "full" };
    }

    // Any comma means a byte-range-SET (multiple ranges), or a
    // malformed list with an empty element ("bytes=0-99,", ",0-99",
    // "0-99,,"). We never build multipart/byteranges, and a partial
    // response to a list-shaped header would be wrong -- so treat the
    // whole class as "serve the full file", never a 206. Splitting and
    // filtering out the empty elements first (as the old code did)
    // would silently let a trailing-comma header through as one range.
    if (unitMatch[1].indexOf(",") !== -1) {
        return { kind: "full" };
    }

    const spec =
        unitMatch[1].trim();

    if (spec.length === 0) {
        // "bytes=" with nothing after it.
        return { kind: "full" };
    }

    const rangeMatch =
        spec.match(/^(\d*)-(\d*)$/);

    if (!rangeMatch) {
        return { kind: "full" };
    }

    const startText = rangeMatch[1];
    const endText = rangeMatch[2];

    if (startText === "" && endText === "") {
        return { kind: "full" };
    }


    // ---- suffix range: "bytes=-N" (the last N bytes) ----
    if (startText === "") {

        const suffixLength =
            Number(endText);

        if (suffixLength === 0 || fileSize === 0) {
            return { kind: "unsatisfiable" };
        }

        if (suffixLength >= fileSize) {
            return { kind: "partial", start: 0, end: fileSize - 1 };
        }

        return {
            kind: "partial",
            start: fileSize - suffixLength,
            end: fileSize - 1
        };

    }


    // ---- normal range: "bytes=S-" or "bytes=S-E" ----
    const start =
        Number(startText);

    const end =
        endText === ""
            ? fileSize - 1
            : Number(endText);

    if (fileSize === 0 || start >= fileSize || end < start) {
        return { kind: "unsatisfiable" };
    }

    return {
        kind: "partial",
        start: start,
        end: Math.min(end, fileSize - 1)
    };

}


/*
    Serve a complete, already-on-disk video file with standards-
    compliant single-range HTTP support (seeking). Used both for
    original files that are already browser-compatible and for files
    that have already been transcoded once and cached to
    TRANSCODED_FOLDER -- from here those two cases are identical: a
    complete file that can be read from an arbitrary byte offset.

    Callers (the /video and /watch routes) resolve `filePath` through
    the media-root containment guard first; this function never
    re-derives a path from user input.
*/
function serveDirectPlay(filePath, req, res) {

    // The callers verify existence first, but a file can still vanish
    // (or become unreadable) between that check and this stat -- keep
    // that a controlled not-found rather than an uncontrolled 500.
    let stat;

    try {
        stat =
            fs.statSync(filePath);
    }
    catch (error) {
        return res
            .status(404)
            .send("Video not found");
    }

    if (!stat.isFile()) {
        return res
            .status(404)
            .send("Video not found");
    }

    const fileSize =
        stat.size;

    const contentType =
        mediaContentType(filePath);

    const parsed =
        parseByteRange(req.headers.range, fileSize);


    // ---- 416: a valid but unsatisfiable single range ----
    if (parsed.kind === "unsatisfiable") {

        res.writeHead(416, {
            "Content-Range": `bytes */${fileSize}`,
            "Accept-Ranges": "bytes",
            "Content-Type": contentType,
            "Content-Length": 0
        });

        return res.end();

    }


    const isPartial =
        parsed.kind === "partial";

    // By construction parsed guarantees 0 <= start <= end <= size-1,
    // so these offsets can never make createReadStream throw a range
    // error the way the old ad-hoc parser could.
    const stream =
        fs.createReadStream(
            filePath,
            isPartial
                ? { start: parsed.start, end: parsed.end }
                : {}
        );


    stream.once("error", (error) => {

        // Lost the file mid-flight. If nothing has been sent yet this
        // is still a clean 404/500; once bytes are on the wire the
        // only safe move is to tear the response down.
        if (res.headersSent || res.writableEnded) {
            res.destroy(error);
            return;
        }

        if (error && error.code === "ENOENT") {
            res.status(404).send("Video not found");
        }
        else {
            res.status(500).end();
        }

    });


    // Release the file descriptor if the viewer seeks away or closes
    // the tab before this chunk finishes -- routine while scrubbing.
    res.on("close", () => {
        stream.destroy();
    });


    stream.once("open", () => {

        if (res.destroyed || res.writableEnded) {
            stream.destroy();
            return;
        }

        if (isPartial) {

            res.writeHead(206, {
                "Content-Range":
                    `bytes ${parsed.start}-${parsed.end}/${fileSize}`,
                "Accept-Ranges": "bytes",
                "Content-Length": (parsed.end - parsed.start) + 1,
                "Content-Type": contentType
            });

        }
        else {

            res.writeHead(200, {
                "Content-Length": fileSize,
                "Content-Type": contentType,
                // Advertise range support on the full-file response
                // too, so a browser knows seeking is available before
                // it ever issues a Range request.
                "Accept-Ranges": "bytes"
            });

        }

        stream.pipe(res);

    });

}


// ============================================================
// VIDEO API
// ============================================================

app.get("/api/videos", (req, res) => {

    const videos = db.prepare(`
        SELECT
            id,
            name,
            relative_path,
            folder,
            size,
            duration,
            width,
            height,
            poster,
            needs_transcode,
            added_at,
            custom_title,
            overview,
            custom_date,
            tagline,
            genres,
            director,
            writers,
            studio,
            release_year,
            backdrop,
            landscape,
            logo,
            video_codec,
            audio_codec
        FROM videos
        ORDER BY added_at DESC
    `).all();

    res.json(videos);

});


// ============================================================
// SAVE MANUAL METADATA (title / overview / date)
// Display-only overrides -- never touches relative_path/name,
// which stay tied to the real file on disk. Admin-gated for the
// same reason profile management and move-original are: it's a
// library-editing action, not a personal per-profile preference.
// ============================================================

app.post(
    "/api/videos/:id/metadata",
    checkAdmin,
    (req, res) => {

        try {

            const id =
                Number(req.params.id);

            if (!Number.isInteger(id)) {

                return res
                    .status(400)
                    .json({
                        error:
                            "Invalid video ID"
                    });

            }


            const {
                title,
                overview,
                date,
                tagline,
                genres,
                director,
                writers,
                studio,
                year
            } = req.body;

            // Empty string clears the field back to "use the
            // default" (raw filename) rather than being rejected --
            // trim so accidental whitespace-only input also clears.
            const cleanTitle =
                (title || "").trim() || null;

            const cleanOverview =
                (overview || "").trim() || null;

            const cleanDate =
                (date || "").trim() || null;

            const cleanTagline =
                (tagline || "").trim() || null;

            const cleanGenres =
                (genres || "").trim() || null;

            const cleanDirector =
                (director || "").trim() || null;

            const cleanWriters =
                (writers || "").trim() || null;

            const cleanStudio =
                (studio || "").trim() || null;

            const cleanYear =
                (year || "").trim() || null;


            const result =
                db.prepare(`
                    UPDATE videos
                    SET
                        custom_title = ?,
                        overview = ?,
                        custom_date = ?,
                        tagline = ?,
                        genres = ?,
                        director = ?,
                        writers = ?,
                        studio = ?,
                        release_year = ?
                    WHERE id = ?
                `).run(
                    cleanTitle,
                    cleanOverview,
                    cleanDate,
                    cleanTagline,
                    cleanGenres,
                    cleanDirector,
                    cleanWriters,
                    cleanStudio,
                    cleanYear,
                    id
                );

            if (result.changes === 0) {

                return res
                    .status(404)
                    .json({
                        error:
                            "Video not found"
                    });

            }


            res.json({ success: true });

        }

        catch (error) {

            console.error(
                "Could not save metadata:",
                error
            );

            res
                .status(500)
                .json({
                    error:
                        "Could not save metadata"
                });

        }

    }
);




// ============================================================
// POPULATE METADATA FROM THE WEB (TMDB)
// Fetches just the basics -- title, overview, year, genres, and
// (if we don't already have a better one) a real poster. Doesn't
// touch relative_path/name. Admin-gated, same as manual editing.
// Shared between the single-video endpoint below and the bulk
// "populate the whole library" background job further down.
// ============================================================

async function populateVideoFromWeb(id) {

    const row =
        db.prepare(`
            SELECT name, custom_title, folder
            FROM videos
            WHERE id = ?
        `).get(id);

    if (!row) {

        return { success: false, status: 404, error: "Video not found" };

    }


    const resolved =
        await poster.resolveVideoMetadata(row);

    if (resolved.error) {

        return {
            success: false,
            status: resolved.status,
            error: resolved.error
        };

    }


    writeMetadataToVideo(id, row.folder, resolved.metadata);


    return { success: true, metadata: resolved.metadata };

}


// Persists resolved metadata to a video row -- episodes and
// movies store slightly different field sets, so this branches
// the same way resolveVideoMetadata does. Shared by the
// single-video endpoint, the bulk job, and the scanner.
function writeMetadataToVideo(id, folder, metadata) {

    if (poster.isEpisodeFolder(folder)) {

        db.prepare(`
            UPDATE videos
            SET
                custom_title = ?,
                overview = ?,
                custom_date = ?,
                genres = ?,
                poster = COALESCE(?, poster)
            WHERE id = ?
        `).run(
            metadata.title,
            metadata.overview,
            metadata.date,
            metadata.genres,
            metadata.poster,
            id
        );

    }

    else {

        db.prepare(`
            UPDATE videos
            SET
                custom_title = ?,
                overview = ?,
                release_year = ?,
                genres = ?,
                poster = COALESCE(?, poster),
                tagline = ?,
                studio = ?,
                director = ?,
                writers = ?,
                backdrop = COALESCE(?, backdrop),
                landscape = COALESCE(?, landscape),
                logo = COALESCE(?, logo)
            WHERE id = ?
        `).run(
            metadata.title,
            metadata.overview,
            metadata.year,
            metadata.genres,
            metadata.poster,
            metadata.tagline,
            metadata.studio,
            metadata.director,
            metadata.writers,
            metadata.backdrop,
            metadata.landscape,
            metadata.logo,
            id
        );

    }

}


app.post(
    "/api/videos/:id/populate-from-web",
    checkAdmin,
    async (req, res) => {

        try {

            const id =
                Number(req.params.id);

            if (!Number.isInteger(id)) {

                return res
                    .status(400)
                    .json({
                        error:
                            "Invalid video ID"
                    });

            }


            const result =
                await populateVideoFromWeb(id);

            if (!result.success) {

                return res
                    .status(result.status)
                    .json({
                        error: result.error
                    });

            }


            res.json({
                success: true,
                metadata: result.metadata
            });

        }

        catch (error) {

            console.error(
                "Could not populate from web:",
                error
            );

            res
                .status(500)
                .json({
                    error:
                        "Could not populate from web"
                });

        }

    }
);


// ============================================================
// BULK POPULATE FROM THE WEB
// Runs populateVideoFromWeb across every video that doesn't
// already have a custom_title (i.e. hasn't been identified yet --
// this never overwrites something already fetched or manually
// entered). Processes one video at a time, in the background, the
// same sequential pattern the scanner's own background conversion
// queue already uses -- never in parallel, since each populate
// call is itself several TMDB requests. The response returns
// immediately; progress is polled via the status endpoint below.
// ============================================================

let bulkPopulateStatus = {
    running: false,
    total: 0,
    completed: 0,
    succeeded: 0,
    failed: 0,
    currentVideo: null,
    errors: [],
    stoppedReason: null
};

app.post(
    "/api/bulk-populate-from-web",
    checkAdmin,
    (req, res) => {

        if (bulkPopulateStatus.running) {

            return res
                .status(409)
                .json({
                    error:
                        "A bulk populate is already running."
                });

        }


        const rows =
            db.prepare(`
                SELECT id, name
                FROM videos
                WHERE custom_title IS NULL
                ORDER BY folder, name
            `).all();

        bulkPopulateStatus = {
            running: true,
            total: rows.length,
            completed: 0,
            succeeded: 0,
            failed: 0,
            currentVideo: null,
            errors: [],
            stoppedReason: null
        };


        res.json({
            started: true,
            total: rows.length
        });


        // Fire-and-forget -- the response above has already been
        // sent, this runs on its own after that.
        (async () => {

            const MAX_CONSECUTIVE_FAILURES = 3;

            let consecutiveFailures = 0;

            for (const row of rows) {

                bulkPopulateStatus.currentVideo =
                    row.name;

                try {

                    const result =
                        await populateVideoFromWeb(row.id);

                    if (result.success) {

                        bulkPopulateStatus.succeeded++;

                        consecutiveFailures = 0;

                    }

                    else {

                        bulkPopulateStatus.failed++;

                        bulkPopulateStatus.errors.push({
                            videoId: row.id,
                            name: row.name,
                            error: result.error
                        });

                        // No API key configured -- every remaining
                        // video would fail the exact same way, so
                        // stop immediately rather than burning
                        // through the whole list pointlessly.
                        if (result.error === "no_api_key") {

                            bulkPopulateStatus.stoppedReason =
                                "No TMDB API key is configured.";

                            break;

                        }

                        consecutiveFailures++;

                        if (consecutiveFailures >= MAX_CONSECUTIVE_FAILURES) {

                            bulkPopulateStatus.stoppedReason =
                                `Stopped after ${MAX_CONSECUTIVE_FAILURES} ` +
                                `failures in a row: ${result.error}`;

                            break;

                        }

                    }

                }

                catch (error) {

                    console.error(
                        "Bulk populate error for video",
                        row.id,
                        error
                    );

                    bulkPopulateStatus.failed++;

                    bulkPopulateStatus.errors.push({
                        videoId: row.id,
                        name: row.name,
                        error: "Unexpected error"
                    });

                    consecutiveFailures++;

                    if (consecutiveFailures >= MAX_CONSECUTIVE_FAILURES) {

                        bulkPopulateStatus.stoppedReason =
                            `Stopped after ${MAX_CONSECUTIVE_FAILURES} ` +
                            `failures in a row.`;

                        break;

                    }

                }

                bulkPopulateStatus.completed++;

                // A small courtesy delay between requests, so a
                // big library doesn't hammer TMDB back-to-back and
                // trigger rate limiting in the first place.
                await new Promise(resolve => setTimeout(resolve, 300));

            }

            bulkPopulateStatus.running = false;

            bulkPopulateStatus.currentVideo = null;

        })();

    }
);


app.get(
    "/api/bulk-populate-status",
    (req, res) => {

        res.json(bulkPopulateStatus);

    }
);


// ============================================================
// MANUAL TMDB SEARCH
// Returns a list of candidate matches for a query the person
// typed themselves (or the auto-guessed one, pre-filled) rather
// than blindly trusting the first result -- the same idea as
// Jellyfin's manual "Identify" search. No downloads, no DB writes.
// ============================================================

app.get(
    "/api/videos/:id/tmdb-search",
    checkAdmin,
    async (req, res) => {

        try {

            const id =
                Number(req.params.id);

            if (!Number.isInteger(id)) {

                return res
                    .status(400)
                    .json({
                        error:
                            "Invalid video ID"
                    });

            }

            const row =
                db.prepare(`
                    SELECT folder
                    FROM videos
                    WHERE id = ?
                `).get(id);

            if (!row) {

                return res
                    .status(404)
                    .json({
                        error:
                            "Video not found"
                    });

            }


            const query =
                (req.query.query || "").trim();

            if (!query) {

                return res
                    .status(400)
                    .json({
                        error:
                            "Enter something to search for."
                    });

            }

            const year =
                (req.query.year || "").trim() || null;


            const result =
                isEpisodeFolder(row.folder)
                    ? await poster.searchTmdbShows(query, year)
                    : await poster.searchTmdbMovies(query, year);

            if (result.error === "no_api_key") {

                return res
                    .status(400)
                    .json({
                        error: "no_api_key"
                    });

            }

            if (result.error) {

                return res
                    .status(502)
                    .json({
                        error: result.error
                    });

            }


            res.json(result);

        }

        catch (error) {

            console.error(
                "Could not search TMDB:",
                error
            );

            res
                .status(500)
                .json({
                    error:
                        "Could not search TMDB"
                });

        }

    }
);


// ============================================================
// APPLY A CHOSEN TMDB MATCH
// Fetches full details for a SPECIFIC, already-known TMDB movie
// id -- no searching involved -- and saves them, the same way
// populate-from-web does. Used once the person has picked which
// search result is actually correct.
// ============================================================

app.post(
    "/api/videos/:id/apply-tmdb-match",
    checkAdmin,
    async (req, res) => {

        try {

            const id =
                Number(req.params.id);

            if (!Number.isInteger(id)) {

                return res
                    .status(400)
                    .json({
                        error:
                            "Invalid video ID"
                    });

            }

            const tmdbId =
                Number(req.body.tmdbId);

            if (!Number.isInteger(tmdbId)) {

                return res
                    .status(400)
                    .json({
                        error:
                            "Invalid TMDB id"
                    });

            }


            const row =
                db.prepare(`
                    SELECT name, custom_title, folder
                    FROM videos
                    WHERE id = ?
                `).get(id);

            if (!row) {

                return res
                    .status(404)
                    .json({
                        error:
                            "Video not found"
                    });

            }


            const episode =
                isEpisodeFolder(row.folder);

            let metadata;

            if (episode) {

                const seasonEpisode =
                    poster.extractSeasonEpisode(row.name);

                if (!seasonEpisode) {

                    return res
                        .status(422)
                        .json({
                            error:
                                `Could not find a season/episode number ` +
                                `(like "S01E02") in "${row.name}".`
                        });

                }

                // Here tmdbId is the SHOW's id (that's what the
                // search results list contains for episodes) --
                // the specific episode still comes from the
                // video's own filename, not from the search pick.
                metadata =
                    await poster.fetchFullEpisodeDetails(
                        tmdbId,
                        seasonEpisode.season,
                        seasonEpisode.episode,
                        row.custom_title || row.name
                    );

            }

            else {

                metadata =
                    await poster.fetchFullMovieDetails(
                        tmdbId,
                        row.custom_title || row.name
                    );

            }

            if (metadata && metadata.error === "no_api_key") {

                return res
                    .status(400)
                    .json({
                        error: "no_api_key"
                    });

            }

            if (metadata && metadata.error) {

                return res
                    .status(502)
                    .json({
                        error: metadata.error
                    });

            }

            if (!metadata) {

                return res
                    .status(404)
                    .json({
                        error:
                            "Could not fetch details for that match."
                    });

            }


            if (episode) {

                db.prepare(`
                    UPDATE videos
                    SET
                        custom_title = ?,
                        overview = ?,
                        custom_date = ?,
                        genres = ?,
                        poster = COALESCE(?, poster)
                    WHERE id = ?
                `).run(
                    metadata.title,
                    metadata.overview,
                    metadata.date,
                    metadata.genres,
                    metadata.poster,
                    id
                );

            }

            else {

                db.prepare(`
                    UPDATE videos
                    SET
                        custom_title = ?,
                        overview = ?,
                        release_year = ?,
                        genres = ?,
                        poster = COALESCE(?, poster),
                        tagline = ?,
                        studio = ?,
                        director = ?,
                        writers = ?,
                        backdrop = COALESCE(?, backdrop),
                        landscape = COALESCE(?, landscape),
                        logo = COALESCE(?, logo)
                    WHERE id = ?
                `).run(
                    metadata.title,
                    metadata.overview,
                    metadata.year,
                    metadata.genres,
                    metadata.poster,
                    metadata.tagline,
                    metadata.studio,
                    metadata.director,
                    metadata.writers,
                    metadata.backdrop,
                    metadata.landscape,
                    metadata.logo,
                    id
                );

            }


            res.json({
                success: true,
                metadata: metadata
            });

        }

        catch (error) {

            console.error(
                "Could not apply TMDB match:",
                error
            );

            res
                .status(500)
                .json({
                    error:
                        "Could not apply TMDB match"
                });

        }

    }
);


// ============================================================
// ADMIN PASSWORD ENDPOINTS
// ============================================================

// Is a password set up yet? Drives whether the profile picker
// prompts for a password (existing setup) or to CREATE one (first
// run). Public -- reveals only a boolean, not the password.
app.get("/api/admin/status", (req, res) => {

    res.json({
        passwordSet: isAdminPasswordSet()
    });

});


// Verify a password (the "log in as Admin" check). Returns
// success so the frontend can unlock admin mode for the session.
// The frontend then reuses the same password as x-admin-key.
app.post("/api/admin/login", (req, res) => {

    try {

        const { password } =
            req.body;

        const storedHash =
            getStoredAdminHash();

        if (!storedHash) {

            return res
                .status(400)
                .json({
                    error: "no_admin_password_set"
                });

        }

        if (!password || !verifyPassword(password, storedHash)) {

            return res
                .status(401)
                .json({
                    error: "Incorrect password."
                });

        }

        res.json({ success: true });

    }

    catch (error) {

        console.error("Admin login error:", error);

        res
            .status(500)
            .json({ error: "Could not verify password" });

    }

});


// Set the admin password. On FIRST setup (no password yet) this
// is open, so a fresh install can bootstrap. To CHANGE an existing
// password, the current one must be supplied and correct.
app.post("/api/admin/set-password", (req, res) => {

    try {

        const { newPassword, currentPassword } =
            req.body;

        if (!newPassword || newPassword.length < 4) {

            return res
                .status(400)
                .json({
                    error:
                        "Password must be at least 4 characters."
                });

        }


        const storedHash =
            getStoredAdminHash();

        // Changing an existing password requires the current one.
        if (storedHash) {

            if (
                !currentPassword ||
                !verifyPassword(currentPassword, storedHash)
            ) {

                return res
                    .status(403)
                    .json({
                        error:
                            "Current password is incorrect."
                    });

            }

        }


        const newHash =
            hashPassword(newPassword);

        db.prepare(`
            INSERT INTO settings (key, value)
            VALUES ('admin_password_hash', ?)
            ON CONFLICT (key)
            DO UPDATE SET value = excluded.value
        `).run(newHash);


        res.json({ success: true });

    }

    catch (error) {

        console.error("Set admin password error:", error);

        res
            .status(500)
            .json({ error: "Could not set password" });

    }

});


// ============================================================
// TMDB API KEY SETTINGS
// Stored in the database (not an env var) so it can be set
// through the UI with no server restart needed. Each install
// gets its own key via the guided setup screen -- never a
// shared/borrowed one baked into the software.
// ============================================================

app.get("/api/settings/tmdb-key", (req, res) => {

    try {

        const key =
            poster.getStoredApiKey();

        res.json({
            configured: !!key,
            // Only send back a masked preview, never the raw key --
            // enough for "yes, ending in ...ab12" confirmation
            // without re-exposing the full secret to the page.
            maskedKey:
                key
                    ? "•".repeat(Math.max(0, key.length - 4)) + key.slice(-4)
                    : null
        });

    }

    catch (error) {

        console.error(
            "Could not load TMDB key status:",
            error
        );

        res
            .status(500)
            .json({
                error:
                    "Could not load TMDB key status"
            });

    }

});


app.post(
    "/api/settings/tmdb-key",
    checkAdmin,
    async (req, res) => {

        try {

            const { apiKey } = req.body;

            if (!apiKey || !apiKey.trim()) {

                return res
                    .status(400)
                    .json({
                        error:
                            "Enter an API key first."
                    });

            }


            const testResult =
                await poster.testApiKey(apiKey);

            if (!testResult.valid) {

                return res
                    .status(400)
                    .json({
                        error: testResult.error
                    });

            }


            poster.saveApiKey(apiKey);


            res.json({ success: true });

        }

        catch (error) {

            console.error(
                "Could not save TMDB key:",
                error
            );

            res
                .status(500)
                .json({
                    error:
                        "Could not save TMDB key"
                });

        }

    }
);


// ============================================================
// PENDING CLEANUP
// Videos the scanner has fully converted to a high-quality
// browser-compatible copy, where the original is still sitting
// in videos/ awaiting a keep/move decision.
// ============================================================

app.get("/api/videos/pending-cleanup", (req, res) => {

    try {

        const rows =
            db.prepare(`
                SELECT id, name, relative_path, size
                FROM videos
                WHERE original_status = 'pending'
            `).all();


        const pending =
            rows
                .map((row) => {

                    const originalPath =
                        path.join(
                            VIDEO_FOLDER,
                            row.relative_path
                        );

                    const cachePath =
                        path.join(
                            TRANSCODED_FOLDER,
                            ffmpeg.getTranscodedRelativePath(row.relative_path)
                        );


                    // Defensive: only ever surface this as
                    // "ready to decide on" if the converted copy
                    // genuinely exists AND the original is still
                    // in videos/ to be moved. Anything else is a
                    // weird intermediate state -- skip it rather
                    // than risk pointing the UI at something
                    // unsafe to act on.
                    if (
                        !fs.existsSync(cachePath) ||
                        !fs.existsSync(originalPath)
                    ) {

                        return null;

                    }


                    const convertedSize =
                        fs.statSync(cachePath).size;


                    return {
                        id: row.id,
                        name: row.name,
                        relative_path: row.relative_path,
                        original_size: row.size,
                        converted_size: convertedSize
                    };

                })
                .filter(item => item !== null);


        res.json(pending);

    }

    catch (error) {

        console.error(
            "Could not load pending cleanup list:",
            error
        );

        res
            .status(500)
            .json({
                error:
                    "Could not load pending cleanup list"
            });

    }

});


// ============================================================
// MOVE AN ORIGINAL FILE OUT OF videos/
// Non-destructive -- the file is relocated to
// NOT_COMPATIBLE_FOLDER (preserving its subfolder structure),
// never deleted. Still admin-gated since it does restructure
// the filesystem, but nothing is ever permanently lost.
// ============================================================

// ============================================================
// MOVE-WITH-FALLBACK HELPER
// A plain rename() fails with EXDEV if source and destination
// are on different drives/filesystems -- falls back to
// copy-then-remove, which works across drives. Shared by both
// the "move the original out" and "move the converted copy in"
// steps below.
// ============================================================

function moveFileWithFallback(sourcePath, destinationPath) {

    fs.mkdirSync(
        path.dirname(destinationPath),
        { recursive: true }
    );

    try {

        fs.renameSync(sourcePath, destinationPath);

    }

    catch (moveError) {

        if (moveError.code === "EXDEV") {

            fs.copyFileSync(sourcePath, destinationPath);

            fs.unlinkSync(sourcePath);

        }

        else {

            throw moveError;

        }

    }

}


app.post(
    "/api/videos/:id/move-original",
    checkAdmin,
    async (req, res) => {

        try {

            const id =
                Number(req.params.id);

            if (!Number.isInteger(id)) {

                return res
                    .status(400)
                    .json({
                        error:
                            "Invalid video ID"
                    });

            }


            const row =
                db.prepare(`
                    SELECT id, relative_path, original_status
                    FROM videos
                    WHERE id = ?
                `).get(id);

            if (!row) {

                return res
                    .status(404)
                    .json({
                        error:
                            "Video not found"
                    });

            }


            const cachePath =
                path.join(
                    TRANSCODED_FOLDER,
                    ffmpeg.getTranscodedRelativePath(row.relative_path)
                );

            // Never move an original unless a working converted
            // copy genuinely exists on disk right now -- refuse
            // even if the DB row claims status is 'pending'.
            if (!fs.existsSync(cachePath)) {

                return res
                    .status(409)
                    .json({
                        error:
                            "No converted copy exists yet -- refusing to move the original"
                    });

            }


            const originalPath =
                path.join(
                    VIDEO_FOLDER,
                    row.relative_path
                );

            const archivePath =
                path.join(
                    NOT_COMPATIBLE_FOLDER,
                    row.relative_path
                );

            // Where the converted copy will end up living --
            // the EXACT same folder the original just vacated,
            // just with a .mp4 extension (the real container
            // format now). This is what makes it show up right
            // next to where the user expects it, instead of in a
            // separate parallel folder tree.
            const newRelativePath =
                ffmpeg.getTranscodedRelativePath(row.relative_path);

            const newVideoPath =
                path.join(VIDEO_FOLDER, newRelativePath);


            if (fs.existsSync(originalPath)) {

                moveFileWithFallback(
                    originalPath,
                    archivePath
                );

            }


            // Defensive: only possible if some unrelated file
            // already happened to occupy this exact spot -- the
            // original's own path was just vacated above, so this
            // is not that file. Refuse rather than risk silently
            // overwriting something else's data.
            if (fs.existsSync(newVideoPath)) {

                return res
                    .status(409)
                    .json({
                        error:
                            "A file already exists at the destination path -- " +
                            "the original was archived, but the converted copy " +
                            "was not moved into place. Please resolve the " +
                            "conflict manually."
                    });

            }


            moveFileWithFallback(
                cachePath,
                newVideoPath
            );


            // Re-probe the file in its new permanent home so the
            // database accurately reflects its real codecs/
            // dimensions/duration, rather than guessing.
            const probeResult =
                await ffmpeg.probeFile(newVideoPath);


            db.prepare(`
                UPDATE videos
                SET
                    relative_path = ?,
                    name = ?,
                    needs_transcode = 0,
                    video_codec = ?,
                    audio_codec = ?,
                    duration = ?,
                    width = ?,
                    height = ?,
                    original_status = 'moved'
                WHERE id = ?
            `).run(
                newRelativePath,
                path.basename(newRelativePath),
                probeResult ? probeResult.videoCodec : null,
                probeResult ? probeResult.audioCodec : null,
                probeResult ? probeResult.duration : null,
                probeResult ? probeResult.width : null,
                probeResult ? probeResult.height : null,
                id
            );


            res.json({
                success: true,
                original_archived_to: archivePath,
                video_now_at: newVideoPath
            });

        }

        catch (error) {

            console.error(
                "Could not move original file:",
                error
            );

            res
                .status(500)
                .json({
                    error:
                        "Could not move original file"
                });

        }

    }
);


// ============================================================
// KEEP THE ORIGINAL (dismiss the pending decision)
// Not destructive, so no admin key required.
// ============================================================

app.post(
    "/api/videos/:id/keep-original",
    (req, res) => {

        try {

            const id =
                Number(req.params.id);

            if (!Number.isInteger(id)) {

                return res
                    .status(400)
                    .json({
                        error:
                            "Invalid video ID"
                    });

            }


            const result =
                db.prepare(`
                    UPDATE videos
                    SET original_status = 'kept'
                    WHERE id = ?
                `).run(id);

            if (result.changes === 0) {

                return res
                    .status(404)
                    .json({
                        error:
                            "Video not found"
                    });

            }


            res.json({ success: true });

        }

        catch (error) {

            console.error(
                "Could not update video:",
                error
            );

            res
                .status(500)
                .json({
                    error:
                        "Could not update video"
                });

        }

    }
);


// ============================================================
// PROFILE API
// ============================================================


// ============================================================
// GET PROFILES
// ============================================================

app.get("/api/profiles", (req, res) => {

    try {

        const profiles =
            db.prepare(`
                SELECT
                    id,
                    name,
                    avatar,
                    created_at
                FROM profiles
                ORDER BY id ASC
            `).all();


        res.json(profiles);

    }

    catch (error) {

        console.error(
            "Could not load profiles:",
            error
        );

        res
            .status(500)
            .json({
                error:
                    "Could not load profiles"
            });

    }

});


// ============================================================
// GET SINGLE PROFILE
// ============================================================

app.get(
    "/api/profiles/:id",
    (req, res) => {

        try {

            const id =
                Number(
                    req.params.id
                );


            if (
                !Number.isInteger(id)
            ) {

                return res
                    .status(400)
                    .json({
                        error:
                            "Invalid profile ID"
                    });

            }


            const profile =
                db.prepare(`
                    SELECT
                        id,
                        name,
                        avatar,
                        created_at
                    FROM profiles
                    WHERE id = ?
                `).get(id);


            if (!profile) {

                return res
                    .status(404)
                    .json({
                        error:
                            "Profile not found"
                    });

            }


            res.json(
                profile
            );

        }

        catch (error) {

            console.error(
                "Could not load profile:",
                error
            );


            res
                .status(500)
                .json({
                    error:
                        "Could not load profile"
                });

        }

    }
);


// ============================================================
// CONTINUE WATCHING API
// ============================================================


// ============================================================
// GET CONTINUE WATCHING
// ============================================================

app.get(
    "/api/continue-watching/:profileId",
    (req, res) => {

        try {

            const profileId =
                Number(
                    req.params.profileId
                );


            if (
                !Number.isInteger(
                    profileId
                )
            ) {

                return res
                    .status(400)
                    .json({
                        error:
                            "Invalid profile ID"
                    });

            }


            const results =
                db.prepare(`
                    SELECT

                        cw.id,

                        cw.profile_id,

                        cw.video_id,

                        cw.position,

                        cw.duration,

                        cw.updated_at,

                        v.name,

                        v.relative_path,

                        v.folder,

                        v.size,

                        v.poster,

                        v.needs_transcode,

                        v.custom_title,

                        v.overview,

                        v.custom_date

                    FROM continue_watching cw

                    INNER JOIN videos v
                        ON v.id = cw.video_id

                    WHERE cw.profile_id = ?

                    AND cw.position > ${START_BUFFER_SECONDS}

                    AND cw.duration > 0

                    AND cw.position <
                        cw.duration - ${END_BUFFER_SECONDS}

                    ORDER BY
                        cw.updated_at DESC

                    LIMIT 10
                `).all(
                    profileId
                );


            res.json(
                results
            );

        }

        catch (error) {

            console.error(
                "Could not load Continue Watching:",
                error
            );


            res
                .status(500)
                .json({
                    error:
                        "Could not load Continue Watching"
                });

        }

    }
);


// ============================================================
// WATCH STATUS FOR SPECIFIC VIDEOS
// Unlike /api/watch-history (capped at 10, most-recent-only),
// this checks exactly the video IDs the caller asks about --
// used by the episode list so a completed episode from a while
// back still correctly shows as completed, not just "not started".
// ============================================================

app.get(
    "/api/watch-status/:profileId",
    (req, res) => {

        try {

            const profileId =
                Number(req.params.profileId);

            if (!Number.isInteger(profileId)) {

                return res
                    .status(400)
                    .json({
                        error:
                            "Invalid profile ID"
                    });

            }


            const videoIds =
                (req.query.videoIds || "")
                    .split(",")
                    .map(Number)
                    .filter(Number.isInteger);

            if (videoIds.length === 0) {

                return res.json({});

            }


            const placeholders =
                videoIds.map(() => "?").join(",");


            const inProgressRows =
                db.prepare(`
                    SELECT video_id, position, duration
                    FROM continue_watching
                    WHERE profile_id = ?
                    AND video_id IN (${placeholders})
                `).all(profileId, ...videoIds);

            const completedRows =
                db.prepare(`
                    SELECT video_id, watched_at
                    FROM watch_history
                    WHERE profile_id = ?
                    AND video_id IN (${placeholders})
                `).all(profileId, ...videoIds);


            const status = {};

            for (const row of inProgressRows) {

                status[row.video_id] = {
                    status: "in_progress",
                    position: row.position,
                    duration: row.duration
                };

            }

            for (const row of completedRows) {

                // In-progress takes precedence if a video somehow
                // has rows in both (shouldn't normally happen,
                // since they're mutually exclusive by design).
                if (!status[row.video_id]) {

                    status[row.video_id] = {
                        status: "completed"
                    };

                }

            }


            res.json(status);

        }

        catch (error) {

            console.error(
                "Could not load watch status:",
                error
            );

            res
                .status(500)
                .json({
                    error:
                        "Could not load watch status"
                });

        }

    }
);


// ============================================================
// GET RECENTLY WATCHED
// The permanent watch_history record, not continue_watching --
// this reflects videos actually finished, most recent first,
// capped at 10.
// ============================================================

app.get(
    "/api/watch-history/:profileId",
    (req, res) => {

        try {

            const profileId =
                Number(req.params.profileId);

            if (!Number.isInteger(profileId)) {

                return res
                    .status(400)
                    .json({
                        error:
                            "Invalid profile ID"
                    });

            }


            const results =
                db.prepare(`
                    SELECT

                        wh.video_id,

                        wh.watched_at,

                        v.name,

                        v.relative_path,

                        v.folder,

                        v.poster,

                        v.needs_transcode,

                        v.custom_title,

                        v.overview,

                        v.custom_date

                    FROM watch_history wh

                    INNER JOIN videos v
                        ON v.id = wh.video_id

                    WHERE wh.profile_id = ?

                    ORDER BY
                        wh.watched_at DESC

                    LIMIT 10
                `).all(
                    profileId
                );


            res.json(results);

        }

        catch (error) {

            console.error(
                "Could not load watch history:",
                error
            );

            res
                .status(500)
                .json({
                    error:
                        "Could not load watch history"
                });

        }

    }
);


// ============================================================
// SAVE CONTINUE WATCHING
// ============================================================

app.post(
    "/api/continue-watching",
    (req, res) => {

        try {

            const {
                profileId,
                videoId,
                position,
                duration
            } = req.body;


            if (
                !Number.isInteger(
                    Number(profileId)
                ) ||
                !Number.isInteger(
                    Number(videoId)
                )
            ) {

                return res
                    .status(400)
                    .json({
                        error:
                            "Invalid profile or video ID"
                    });

            }


            const cleanProfileId =
                Number(
                    profileId
                );


            const cleanVideoId =
                Number(
                    videoId
                );


            const cleanPosition =
                Number(
                    position
                );


            const cleanDuration =
                Number(
                    duration
                );


            if (
                !Number.isFinite(
                    cleanPosition
                ) ||
                !Number.isFinite(
                    cleanDuration
                )
            ) {

                return res
                    .status(400)
                    .json({
                        error:
                            "Invalid playback position"
                    });

            }


            // ----------------------------------------------------
            // REJECT NONSENSICAL VALUES
            // A negative position, a zero/negative duration, or
            // a position past the end of the video should never
            // be written to the database.
            // ----------------------------------------------------

            if (
                cleanPosition < 0 ||
                cleanDuration <= 0
            ) {

                return res
                    .status(400)
                    .json({
                        error:
                            "Position and duration must be positive"
                    });

            }


            // Clamp instead of rejecting: players sometimes report
            // a position a fraction of a second past duration due
            // to float rounding right at the end of playback.
            const safePosition =
                Math.min(
                    cleanPosition,
                    cleanDuration
                );


            // ----------------------------------------------------
            // VERIFY PROFILE EXISTS
            // ----------------------------------------------------

            const profile =
                db.prepare(`
                    SELECT
                        id
                    FROM profiles
                    WHERE id = ?
                `).get(
                    cleanProfileId
                );


            if (!profile) {

                return res
                    .status(404)
                    .json({
                        error:
                            "Profile not found"
                    });

            }


            // ----------------------------------------------------
            // VERIFY VIDEO EXISTS
            // ----------------------------------------------------

            const video =
                db.prepare(`
                    SELECT
                        id
                    FROM videos
                    WHERE id = ?
                `).get(
                    cleanVideoId
                );


            if (!video) {

                return res
                    .status(404)
                    .json({
                        error:
                            "Video not found"
                    });

            }


            // ----------------------------------------------------
            // JUST STARTED OR FINISHED -> DON'T KEEP A ROW
            // Same thresholds the GET endpoint uses to hide these
            // entries. Deleting here (instead of only filtering on
            // read) means the table never accumulates dead rows for
            // videos that are done or barely begun.
            // ----------------------------------------------------

            const isJustStarted =
                safePosition <= START_BUFFER_SECONDS;

            const isFinished =
                safePosition >=
                cleanDuration - END_BUFFER_SECONDS;


            if (isJustStarted || isFinished) {

                db.prepare(`
                    DELETE FROM continue_watching
                    WHERE profile_id = ?
                    AND video_id = ?
                `).run(
                    cleanProfileId,
                    cleanVideoId
                );


                // Only a genuine finish counts as "watched" --
                // not a reset from barely starting it.
                if (isFinished) {

                    db.prepare(`
                        INSERT INTO watch_history
                        (
                            profile_id,
                            video_id,
                            watched_at
                        )

                        VALUES
                        (
                            ?,
                            ?,
                            CURRENT_TIMESTAMP
                        )

                        ON CONFLICT (
                            profile_id,
                            video_id
                        )

                        DO UPDATE SET

                            watched_at =
                                CURRENT_TIMESTAMP

                    `).run(
                        cleanProfileId,
                        cleanVideoId
                    );

                }


                return res.json({
                    success: true,
                    tracked: false
                });

            }


            // ----------------------------------------------------
            // SAVE / UPDATE PROGRESS
            // ----------------------------------------------------

            db.prepare(`
                INSERT INTO continue_watching
                (
                    profile_id,
                    video_id,
                    position,
                    duration,
                    updated_at
                )

                VALUES
                (
                    ?,
                    ?,
                    ?,
                    ?,
                    CURRENT_TIMESTAMP
                )

                ON CONFLICT (
                    profile_id,
                    video_id
                )

                DO UPDATE SET

                    position =
                        excluded.position,

                    duration =
                        excluded.duration,

                    updated_at =
                        CURRENT_TIMESTAMP

            `).run(

                cleanProfileId,

                cleanVideoId,

                safePosition,

                cleanDuration

            );


            res.json({
                success: true,
                tracked: true
            });

        }

        catch (error) {

            console.error(
                "Could not save Continue Watching:",
                error
            );


            res
                .status(500)
                .json({
                    error:
                        "Could not save Continue Watching"
                });

        }

    }
);


// ============================================================
// REMOVE FINISHED VIDEO
// ============================================================

app.delete(
    "/api/continue-watching/:profileId/:videoId",
    (req, res) => {

        try {

            const profileId =
                Number(
                    req.params.profileId
                );


            const videoId =
                Number(
                    req.params.videoId
                );


            if (
                !Number.isInteger(
                    profileId
                ) ||
                !Number.isInteger(
                    videoId
                )
            ) {

                return res
                    .status(400)
                    .json({
                        error:
                            "Invalid profile or video ID"
                    });

            }


            db.prepare(`
                DELETE FROM continue_watching

                WHERE profile_id = ?

                AND video_id = ?
            `).run(

                profileId,

                videoId

            );


            res.json({
                success: true
            });

        }

        catch (error) {

            console.error(
                "Could not remove Continue Watching item:",
                error
            );


            res
                .status(500)
                .json({
                    error:
                        "Could not remove Continue Watching item"
                });

        }

    }
);


// ============================================================
// ADMIN AUTHENTICATION
// ============================================================

function checkAdmin(req, res, next) {

    const storedHash =
        getStoredAdminHash();

    // No password set up yet -- fall back to the env var if one's
    // configured (keeps existing installs working), otherwise the
    // very first password-set call is allowed through by its own
    // endpoint, not here.
    if (!storedHash) {

        const envKey =
            process.env.BASEFLIX_ADMIN_KEY;

        if (envKey && req.headers["x-admin-key"] === envKey) {

            return next();

        }

        return res
            .status(403)
            .json({
                error:
                    "no_admin_password_set"
            });

    }


    const suppliedKey =
        req.headers["x-admin-key"];

    if (
        !suppliedKey ||
        !verifyPassword(suppliedKey, storedHash)
    ) {

        return res
            .status(403)
            .json({
                error:
                    "Admin access required"
            });

    }


    next();

}


// ============================================================
// CREATE PROFILE
// ADMIN ONLY
// ============================================================

app.post(
    "/api/profiles",
    checkAdmin,
    (req, res) => {

        try {

            const {
                name,
                avatar
            } = req.body;


            if (
                !name ||
                !name.trim()
            ) {

                return res
                    .status(400)
                    .json({
                        error:
                            "Profile name is required"
                    });

            }


            const cleanName =
                name.trim();


            const cleanAvatar =
                avatar ||
                "🎬";


            const result =
                db.prepare(`
                    INSERT INTO profiles
                    (
                        name,
                        avatar
                    )

                    VALUES
                    (
                        ?,
                        ?
                    )
                `).run(
                    cleanName,
                    cleanAvatar
                );


            res.json({
                success: true,
                id: result.lastInsertRowid
            });

        }

        catch (error) {

            if (
                error.code ===
                "SQLITE_CONSTRAINT_UNIQUE"
            ) {

                return res
                    .status(409)
                    .json({
                        error:
                            "A profile with that name already exists"
                    });

            }


            console.error(
                "Could not create profile:",
                error
            );


            res
                .status(500)
                .json({
                    error:
                        "Could not create profile"
                });

        }

    }
);


// ============================================================
// DELETE PROFILE
// ADMIN ONLY
// ============================================================

app.delete(
    "/api/profiles/:id",
    checkAdmin,
    (req, res) => {

        try {

            const id =
                Number(
                    req.params.id
                );


            if (
                !Number.isInteger(id)
            ) {

                return res
                    .status(400)
                    .json({
                        error:
                            "Invalid profile ID"
                    });

            }


            const profile =
                db.prepare(`
                    SELECT
                        id,
                        name
                    FROM profiles
                    WHERE id = ?
                `).get(id);


            if (!profile) {

                return res
                    .status(404)
                    .json({
                        error:
                            "Profile not found"
                    });

            }


            // Prevent deleting Admin.

            if (
                profile.name ===
                "Admin"
            ) {

                return res
                    .status(403)
                    .json({
                        error:
                            "The Admin profile cannot be deleted"
                    });

            }


            db.prepare(`
                DELETE FROM profiles
                WHERE id = ?
            `).run(id);


            res.json({
                success: true
            });

        }

        catch (error) {

            console.error(
                "Could not delete profile:",
                error
            );


            res
                .status(500)
                .json({
                    error:
                        "Could not delete profile"
                });

        }

    }
);


// ============================================================
// VIDEO PLAYER PAGE
// ============================================================

// Minimal HTML-escaping so a crafted filename can't break out
// of the page (defense in depth — these are your own files,
// but cheap to guard against anyway).
function escapeHtml(text) {

    return String(text)
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;");

}


app.get("/watch/:filename", (req, res) => {

    // Express already decodes route params (including a %2F
    // that was encoding a literal "/" within this single
    // segment) before handlers ever see them -- decoding again
    // here would be redundant at best, and would throw on any
    // filename containing a literal "%" character at worst.
    const filename =
        req.params.filename;

    // Containment: the decoded segment is attacker-controlled, so
    // resolve it through the shared media-root guard rather than
    // path.join'ing it straight onto VIDEO_FOLDER. null => it escaped
    // the media root (or is malformed) -- answer exactly as for a
    // missing file, no information disclosure.
    const videoPath =
        resolveMediaFilePath(VIDEO_FOLDER, filename);


    if (videoPath === null || !fs.existsSync(videoPath)) {

        return res
            .status(404)
            .send("Video not found");

    }


    // Look up the video's database id so the page can report
    // playback progress back to /api/continue-watching. If the
    // file exists on disk but hasn't been scanned into the DB
    // yet, videoId will be null and progress tracking is skipped.
    const video =
        db.prepare(`
            SELECT id, name
            FROM videos
            WHERE relative_path = ?
        `).get(filename);

    const videoId =
        video ? video.id : null;

    const safeTitle =
        escapeHtml(
            video ? video.name : filename
        );


    res.send(`
        <!DOCTYPE html>

        <html>

        <head>

            <meta charset="UTF-8">

            <title>${safeTitle}</title>

            <style>

                body {
                    background: #101010;
                    color: #eee;
                    font-family: sans-serif;
                    margin: 0;
                    padding: 24px;
                }

                h1 {
                    font-size: 1.2rem;
                    font-weight: normal;
                    margin: 0 0 16px;
                }

                video {
                    display: block;
                    width: 90%;
                    max-width: 1200px;
                    background: black;
                }

                a.back {
                    color: #9fc7ff;
                    text-decoration: none;
                    display: inline-block;
                    margin-bottom: 16px;
                }

            </style>

        </head>

        <body>

            <a class="back" href="/">&larr; Back to Home</a>

            <h1>${safeTitle}</h1>

            <video
                id="player"
                controls
                autoplay
                style="
                    width: 90%;
                    max-width: 1200px;
                "
            >

                <source
                    src="/video/${encodeURIComponent(filename)}"
                >

                Your browser does not
                support video playback.

            </video>

            <script>
                (function () {

                    var videoId = ${JSON.stringify(videoId)};
                    var profileId = localStorage.getItem("baseflixProfileId");
                    var player = document.getElementById("player");

                    // No profile selected yet, or this file isn't
                    // in the library DB (e.g. not scanned) -- skip
                    // progress tracking entirely.
                    if (!videoId || !profileId) {
                        return;
                    }

                    var saveTimer = null;

                    function saveProgress() {

                        var duration = player.duration;
                        var position = player.currentTime;

                        if (!isFinite(duration) || duration <= 0) {
                            return;
                        }

                        fetch("/api/continue-watching", {
                            method: "POST",
                            headers: { "Content-Type": "application/json" },
                            body: JSON.stringify({
                                profileId: Number(profileId),
                                videoId: videoId,
                                position: position,
                                duration: duration
                            })
                        }).catch(function (err) {
                            console.error("Could not save progress:", err);
                        });

                    }

                    // Resume from saved position, if any.
                    fetch("/api/continue-watching/" + profileId)
                        .then(function (res) { return res.json(); })
                        .then(function (items) {

                            var match = items.find(function (item) {
                                return item.video_id === videoId;
                            });

                            if (match) {
                                player.currentTime = match.position;
                            }

                        })
                        .catch(function (err) {
                            console.error("Could not load resume position:", err);
                        });

                    player.addEventListener("play", function () {
                        saveTimer = setInterval(saveProgress, 5000);
                    });

                    player.addEventListener("pause", function () {
                        clearInterval(saveTimer);
                        saveProgress();
                    });

                    player.addEventListener("ended", function () {
                        clearInterval(saveTimer);
                        saveProgress();
                    });

                    window.addEventListener("beforeunload", function () {
                        clearInterval(saveTimer);
                        saveProgress();
                    });

                })();
            </script>

        </body>

        </html>
    `);

});


// ============================================================
// PLAYBACK DECISION (diagnostic)  -- Task 7
//
// probe -> capabilities -> decidePlayback, returned as JSON. This is
// how the server RECEIVES normalized client capability information
// (request body `client`, or the X-Baseflix-Client-Capabilities
// header / ?caps= query) and how a caller can inspect what the
// engine would choose. It performs NO remux/transcode and does not
// change how /video streams. All rules live in playback-decision.js.
// ============================================================

app.post("/api/playback/decision", async (req, res) => {

    try {

        const requested =
            (req.body && typeof req.body.path === "string") ? req.body.path : "";

        if (!requested) {
            return res
                .status(400)
                .json({ error: "A media 'path' (relative_path) is required" });
        }

        // Task 2 containment -- identical guard to /video and /watch.
        const mediaPath =
            resolveMediaFilePath(VIDEO_FOLDER, requested);

        // Only decide for files that are actually in the library.
        const row =
            db.prepare(`
                SELECT id, relative_path, video_codec, audio_codec, width, height, size
                FROM videos
                WHERE relative_path = ?
            `).get(requested);

        if (mediaPath === null || !row || !fs.existsSync(mediaPath)) {
            return res
                .status(404)
                .json({ error: "Media not found" });
        }

        const clientCapabilities =
            (req.body && req.body.client !== undefined)
                ? req.body.client
                : playbackIntegration.readClientCapabilities(req);

        const result =
            await playbackIntegration.probeAndDecide(mediaPath, clientCapabilities);

        res.json({
            decision: result.decision,
            media: playbackIntegration.summarizeProbe(result.probe)
        });

    }
    catch (error) {

        console.error("Playback decision endpoint failed:", error);

        res
            .status(500)
            .json({ error: "Could not compute a playback decision" });

    }

});


// ============================================================
// VIDEO STREAM
// ============================================================

app.get("/video/:filename", async (req, res) => {

    // Express already decodes route params (including a %2F
    // that was encoding a literal "/" within this single
    // segment) before handlers ever see them -- decoding again
    // here would be redundant at best, and would throw on any
    // filename containing a literal "%" character at worst.
    const filename =
        req.params.filename;

    // Containment: the decoded segment is attacker-controlled. Both
    // the source path and the derived cache path go through the shared
    // media-root guard -- a null result means it resolved outside its
    // root (traversal, absolute path, prefix sibling, symlink escape)
    // and is treated as "not present", identical to a genuine miss.
    const videoPath =
        resolveMediaFilePath(VIDEO_FOLDER, filename);


    // Look up whether this file was flagged during scanning as
    // needing a transcode. If it hasn't been scanned yet (no row,
    // or needs_transcode is still NULL), default to direct play --
    // matches the original behavior rather than blocking playback
    // on a probe that hasn't run yet. The lookup is unchanged: still
    // keyed on the raw relative_path exactly as stored by the scanner.
    const videoRow =
        db.prepare(`
            SELECT id, needs_transcode, video_codec, audio_codec, width, height, size
            FROM videos
            WHERE relative_path = ?
        `).get(filename);

    const needsTranscode =
        videoRow &&
        videoRow.needs_transcode === 1;

    const cachePath =
        videoRow
            ? resolveMediaFilePath(
                TRANSCODED_FOLDER,
                ffmpeg.getTranscodedRelativePath(filename)
            )
            : null;

    const cacheExists =
        cachePath !== null &&
        fs.existsSync(cachePath);

    const originalExists =
        videoPath !== null &&
        fs.existsSync(videoPath);


    // The original may have been moved out of videos/ (with
    // approval, once a converted copy exists -- see
    // /api/videos/:id/move-original above) -- that's fine as long
    // as the converted copy is there to serve instead. Only a
    // genuine "neither exists" is a 404.
    if (!originalExists && !cacheExists) {

        return res
            .status(404)
            .send("Video not found");

    }


    // --------------------------------------------------------
    // PLAYBACK DECISION -- Task 7 boundary + Task 8 Direct Play gate.
    //
    // probe -> capabilities -> decidePlayback, obtained ONLY through
    // playback-integration.js (no codec/container/capability rules
    // live here). When -- and only when -- the decision engine
    // EXPLICITLY returns DIRECT_PLAY, the request is routed onto the
    // hardened Task 3 serveDirectPlay() path for the original file.
    //
    // REMUX / AUDIO_TRANSCODE / VIDEO_TRANSCODE are NOT executed here:
    // any non-DIRECT_PLAY decision -- and any failure to decide --
    // falls through to the existing playback logic below, unchanged.
    //
    // Conservative rule (Task 6) is preserved: missing / unknown
    // capabilities never produce DIRECT_PLAY, so such a request takes
    // the existing safe fallback rather than a decision-gated direct
    // serve.
    // --------------------------------------------------------
    let playbackMode = null;
    let playbackBasis = "fallback";
    let playbackTarget = null;

    try {

        const resolved =
            await playbackIntegration.resolvePlaybackMode({
                filePath: videoPath || (cacheExists ? cachePath : null),
                row: videoRow,
                needsTranscode: needsTranscode,
                clientCapabilities:
                    playbackIntegration.readClientCapabilities(req)
            });

        playbackMode = resolved.mode;
        playbackBasis = resolved.basis;
        playbackTarget = resolved.target || null;

        if (playbackMode) {
            res.setHeader("X-Baseflix-Playback-Mode", playbackMode);
        }

    }
    catch (decisionError) {

        console.error(
            "Playback decision failed; using existing fallback:",
            decisionError.message
        );

    }


    // Task 8: the engine explicitly permits Direct Play -> serve the
    // ORIGINAL file through the hardened path. (If the original was
    // moved out and only a cache exists, fall through -- the existing
    // logic serves the cache.)
    if (playbackMode === "direct_play" && originalExists) {

        res.setHeader("X-Baseflix-Playback", "direct-play");
        res.setHeader("X-Baseflix-Playback-Basis", playbackBasis);

        return serveDirectPlay(videoPath, req, res);

    }


    // Task 9: the engine chose REMUX -> stream-copy the original into
    // the client-supported container Task 6 already picked, cache it,
    // and serve the COMPLETED file through the same hardened path (so
    // Range/206/416 all work). AUDIO_TRANSCODE / VIDEO_TRANSCODE are
    // NOT executed here -- they fall through to the existing logic.
    // If the remux fails or times out, the request falls back too;
    // it is never reported as a successful remux.
    if (playbackMode === "remux" && originalExists && playbackTarget) {

        const remuxAbort = new AbortController();
        res.on("close", () => remuxAbort.abort());

        let remuxResult = null;

        try {
            remuxResult =
                await remux.ensureRemux({
                    sourcePath: videoPath,
                    relativePath: filename,
                    container: playbackTarget,
                    signal: remuxAbort.signal
                });
        }
        catch (remuxError) {
            console.error(
                "Remux failed; using existing fallback:",
                remuxError && remuxError.message
            );
        }

        if (
            remuxResult && remuxResult.ok &&
            !res.writableEnded && !res.destroyed
        ) {
            res.setHeader("X-Baseflix-Playback", "remux");
            res.setHeader("X-Baseflix-Playback-Target", remuxResult.container);
            return serveDirectPlay(remuxResult.path, req, res);
        }

        // remux unavailable -> fall through to the existing behaviour
    }

    res.setHeader("X-Baseflix-Playback", "fallback");


    if (!needsTranscode) {

        // Non-transcoded files are never converted/cached, so the
        // original is the only copy -- if it's gone, there's
        // nothing else to serve.
        if (!originalExists) {

            return res
                .status(404)
                .send("Video not found");

        }

        return serveDirectPlay(videoPath, req, res);

    }


    // --------------------------------------------------------
    // ALREADY CACHED (from an earlier play, or the scanner's
    // background conversion)?
    // Serve the cached copy exactly like any other complete file,
    // seeking included. No need to pay the transcoding cost again
    // -- and this is the only option left if the original was
    // already deleted.
    // --------------------------------------------------------

    if (cacheExists) {

        return serveDirectPlay(cachePath, req, res);

    }


    if (!originalExists) {

        // Needs transcoding, no cache yet, and the original is
        // also gone -- genuinely nothing left to serve.
        return res
            .status(404)
            .send("Video not found");

    }


    // --------------------------------------------------------
    // LIVE TRANSCODE PATH
    // No range-request support on THIS request -- it's a single
    // live ffmpeg pipe, so seeking to an arbitrary timestamp isn't
    // possible yet. The output is simultaneously written to
    // TRANSCODED_FOLDER, though, so every future request for this
    // same file hits the cached-file branch above instead and
    // gets normal, fully-seekable playback.
    // --------------------------------------------------------

    // Re-derive which specific track(s) are the actual problem
    // from the codecs recorded during scanning (cheap -- no new
    // ffprobe call needed). Only re-encode the track(s) that
    // actually need it: re-encoding video you don't need to touch
    // is pure wasted CPU, and is a big part of why a transcode can
    // fail to keep up with real-time playback.
    const playability =
        ffmpeg.checkPlayability({
            videoCodec: videoRow.video_codec,
            audioCodec: videoRow.audio_codec
        });

    res.writeHead(200, {

        "Content-Type":
            "video/mp4"

        // Deliberately no Content-Length (unknown ahead of time)
        // and no Accept-Ranges (seeking isn't supported on this
        // particular request -- only on the cached file it
        // produces for next time).

    });


    let ffmpegProcess = null;


    // If the viewer closes the tab/player before the transcode
    // finishes, kill ffmpeg instead of leaving it running to
    // completion in the background.
    //
    // NOTE: this listens on the RESPONSE's close event, not the
    // request's. A bodyless GET request's own stream closes
    // almost immediately (there's no body to read), long before
    // the response finishes -- listening there would kill ffmpeg
    // right at the start of every single transcode. res.writableEnded
    // tells us whether this close is a normal finish or a real
    // early disconnect.
    res.on("close", () => {

        if (ffmpegProcess && !res.writableEnded) {

            ffmpegProcess.kill("SIGKILL");

        }

    });


    ffmpeg
        .transcodeToMp4Stream(
            videoPath,
            res,
            {
                copyVideo: playability.videoOk,
                copyAudio: playability.audioOk,
                maxHeight: MAX_TRANSCODE_HEIGHT,
                cacheFilePath: cachePath
            },
            (spawnedProcess) => {
                ffmpegProcess = spawnedProcess;
            }
        )
        .then((result) => {

            if (result && result.cachedComplete) {

                console.log(
                    `Cached transcode for future plays: ${filename}`
                );

            }

        })
        .catch((error) => {

            console.error(
                `Transcode failed for ${filename}:`,
                error.message
            );


            if (!res.headersSent) {

                res.status(500).end();

            }

            else {

                res.end();

            }

        });

});


// ============================================================
// SCAN VIDEO LIBRARY
// ============================================================

scanner.scanLibrary().catch((error) => {

    console.error(
        "Library scan failed:",
        error
    );

});


// ============================================================
// START BASEFLIX
// ============================================================

app.listen(
    PORT,
    "0.0.0.0",
    () => {

        console.log(
            `🎬 Baseflix running on port ${PORT}`
        );

    }
);